// fixtures/figures-book.pdf: 6 pages with two pictures and one drawn diagram, each with a "Figure" caption the text refers to
const { chromium } = require('playwright'); const fs = require('fs');
const img = 'data:image/png;base64,' + fs.readFileSync(__dirname + '/fixtures/brain.png').toString('base64');
const P = t => `<p>${t}</p>`;
const filler = 'Researchers study how the brain supports learning and memory. Each region has a role, and damage to one region changes behaviour in ways that can be measured in careful experiments over time.';
const html = `<style>@page{size:A4;margin:22mm 20mm}body{font:11.5pt/1.55 Georgia,serif}h1{font:700 26pt Helvetica,Arial;margin:0 0 14pt}h2{font:700 16pt Helvetica,Arial;margin:18pt 0 8pt}figure{margin:14pt 0;text-align:center}figcaption{font:italic 10pt Georgia;margin-top:6pt}img{width:300px}.b{break-after:page}</style>
<h1>2 The brain</h1><h2>2.1 Parts of the brain</h2>${P(filler)}${P('Figure 2.1 shows the four lobes of the brain and where each one sits. The frontal lobe plans actions, while the occipital lobe processes what we see.')}
<figure><img src="${img}"><figcaption>Figure 2.1 The four lobes of the human brain</figcaption></figure>${P(filler)}<div class="b"></div>
<h2>2.2 The hippocampus</h2>${P(filler)}${P('The hippocampus is a curved structure deep in the temporal lobe that is needed to form new long-term memories. As Figure 2.2 shows, it sits next to the amygdala.')}
<figure><img src="${img}" style="width:240px"><figcaption>Figure 2.2 The hippocampus and amygdala</figcaption></figure>${P(filler.repeat(2))}<div class="b"></div>
<h2>2.3 The memory pathway</h2>${P(filler)}${P('Figure 2.3 summarises the pathway from sensory input to long-term storage. Information that is rehearsed moves from short-term memory into long-term memory.')}
<figure><svg width="420" height="170" viewBox="0 0 420 170" font-family="Helvetica" font-size="12"><rect x="5" y="60" width="110" height="44" rx="8" fill="none" stroke="#123" stroke-width="2"/><text x="20" y="87">Sensory input</text><path d="M115 82h40" stroke="#123" stroke-width="2"/><rect x="155" y="60" width="110" height="44" rx="8" fill="none" stroke="#123" stroke-width="2"/><text x="170" y="87">Short-term</text><path d="M265 82h40" stroke="#123" stroke-width="2"/><rect x="305" y="60" width="110" height="44" rx="8" fill="none" stroke="#123" stroke-width="2"/><text x="322" y="87">Long-term</text><text x="185" y="140">rehearsal</text></svg><figcaption>Figure 2.3 The memory pathway</figcaption></figure>${P(filler.repeat(3))}`;
(async () => { const b = await chromium.launch(); const p = await b.newPage(); await p.setContent(html); await p.pdf({ path: __dirname + '/fixtures/figures-book.pdf', format: 'A4', displayHeaderFooter: true, headerTemplate: '<span></span>', footerTemplate: '<div style="font-size:9px;width:100%;text-align:center"><span class="pageNumber"></span></div>', margin: { top: '22mm', bottom: '22mm', left: '20mm', right: '20mm' } }); await b.close(); console.log('ok'); })();
